language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
    - python3.6 -m unittest discover test/
    - sh test/typecheck.sh
