sdk: '2'
go-runtime:
  version: '1.13-alpine'
native:
  image: 'python:3.6-alpine'
  deps:
    - 'apk add python2'
  static:
    - path: 'native.sh'
      dest: 'native'
  build:
    image: 'python:3.6-alpine'
    run:
      - 'pip3 install -U --prefix=./.local ./python_package'
    artifacts:
      - path: '/native/.local'
        dest: '.local'
  test:
    run:
      - 'cd ./python_package/test && PYTHONPATH=../../.local:$PYTHONPATH python3 -m unittest discover'
